# Build stage
# Build stage
FROM golang:1.21.0-alpine3.17 AS build
WORKDIR /app
COPY . .
RUN go build -o main .
# Ensure the binary has execute permissions
RUN chmod +x main

# Run stage with Alpine for debugging
FROM alpine:3.17
WORKDIR /app
COPY --from=build /app/main .
EXPOSE 8001
CMD ["/app/main"]
